# Use postgres/example user/password credentials
version: '3.8'

services:

  notitication:
    image: notitication:1.0.0
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/notification
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test123
    deploy:
          resources:
            limits:
              cpus: '0.15'
              memory: 1024M
            reservations:
              cpus: '0.05'
              memory: 256M

