# Use postgres/example user/password credentials
version: '3.1'

services:

  notitication:
    image: notitication:1.0.0
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/notification
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test123

