# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
        POSTGRES_DB: notification
      POSTGRES_USER: user
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
